### ISSUE TITLE
SpringNavigator won't initialize

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-testing-spring#4]
I can't seem to get the SpringNavigator to initialize in the tests. When I `@Autowire SpringNavigator navigator;` into `MainUI`, then try to `setNavigator(navigator)` in MainUI.init(), I'll get

```
Caused by: java.lang.NullPointerException
	at com.vaadin.navigator.Navigator.getState(Navigator.java:912)
	at com.vaadin.ui.UI.doInit(UI.java:776)
	at com.github.mvysny.kaributesting.v8.MockVaadin.createUI(MockVaadin.kt:214)
```

The StateManager is not being created for some reason. Can any Spring enthusiast help?

**Comment by mvysny** [comment]
Ah right I forgot to call navigator.init()
