### ISSUE TITLE
Error when using @RouteScope in components

### ISSUE THREAD

**Issue by brunovianarezende** [mvysny/karibu-testing-spring#9]
I have a component annotated with @RouteScope and when I try to init the app in the test, I get the error:

```
Caused by: java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener registered?
	at org.springframework.web.context.support.WebApplicationContextUtils.getRequiredWebApplicationContext(WebApplicationContextUtils.java:85)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.getContext(VaadinRouteScope.java:372)
```

This is the code in my test class:

```
  private static final Routes routes = new Routes().autoDiscoverViews("the.package");

  @Autowired
  private ApplicationContext ctx;

  @BeforeEach
  public void mockVaadin() {
    final Function0<UI> uiFactory = UI::new;
    final SpringServlet servlet = new MockSpringServlet(routes, ctx, uiFactory);
    MockVaadin.setup(uiFactory, servlet);
  }
```

To fix this error, I've changed the mockVaadin() function to:

```
  @BeforeEach
  public void mockVaadin() {
    final Function0<UI> uiFactory = UI::new;
    final SpringServlet servlet = new MockSpringServlet(routes, ctx, uiFactory);
    MockVaadin.setup(uiFactory, servlet);
    servlet.getServletContext()
        .setAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE, ctx);
  }
```

I think we should do this setup somewhere in karibu. My first idea is to add the code that sets the WebAplicationContext inside `MockVaadin.setup`. What do you think?

**Comment by brunovianarezende** [comment]
ops, it seems like I opened the issue in the wrong repository....
